spring:
    profiles:
        active: dev

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/spring_blog
      username: root
      password: 

    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

